// ─── Faction definitions ──────────────────────────────────────────────────────
export const FACTIONS = {
  EMBERVEIL: { name: 'EMBERVEIL', color: '#FF4500', accent: '#FF6B35', element: 'Fire',  lore: 'Masters of volcanic flame and storm energy. Born from the erupting highlands, EMBERVEIL warriors channel raw elemental destruction into devastating combat arts. Their sovereign commands fire from beyond the dimensional veil itself.' },
  GLACIARA:  { name: 'GLACIARA',  color: '#00B4D8', accent: '#90E0EF', element: 'Ice',   lore: 'Ancient wielders of absolute zero. GLACIARA mages and warriors have spent centuries hardening body and soul against the eternal frost, forging power that no other element can withstand. Their sovereign once sealed an elder darkness at the cost of her throne.' },
  SUNSPIRE:  { name: 'SUNSPIRE',  color: '#D4A017', accent: '#F5C842', element: 'Holy',  lore: 'Champions of sacred radiance and divine light. SUNSPIRE clerics and paladins channel the power of the sun itself into both healing grace and annihilating judgment. Their sovereign was chosen not by bloodline — but by the light.' },
  VERDANIA:  { name: 'VERDANIA',  color: '#2ECC71', accent: '#A8E6CF', element: 'Nature', lore: 'Guardians of the ancient forest and living earth. VERDANIA warriors fight as one with the natural world, commanding roots, thorns, and primordial growth that overwhelms enemies from all directions. Their sovereign is the forest itself given human form.' },
  VOIDMARK:  { name: 'VOIDMARK',  color: '#9B59B6', accent: '#D7BDE2', element: 'Void',  lore: 'Void sorcerers from the abyss between dimensions. VOIDMARK operatives weaponise dimensional tears and shadow energy that tears reality itself. Their sovereign has merged with the void and been reborn — undefeatable, absolute.' },
};

// ─── Rank colors ─────────────────────────────────────────────────────────────
export const RANK_COLORS = {
  SOVEREIGN: { bg: '#FFD700', text: '#1A0A00', glow: '#FFEC6E' },
  S:         { bg: '#F72585', text: '#FFF',    glow: '#FF85C2' },
  A:         { bg: '#7B2FBE', text: '#E9D5FF', glow: '#C084FC' },
  B:         { bg: '#0284C7', text: '#E0F2FE', glow: '#7DD3FC' },
  C:         { bg: '#059669', text: '#D1FAE5', glow: '#6EE7B7' },
};

// ─── All 53 heroes ────────────────────────────────────────────────────────────
export const HEROES = [
  { id:'hero_001', name:'Kira Voltz',     frame:'STORMCALLER',    faction:'EMBERVEIL', rank:'S',         element:'Lightning', effect:'PARALYSIS',       class:'Attacker', cardId:'EMB-01-KIRA',     hp:3400, atk:600, def:185, crit:550, about:'A relentless thunder mage who channels raw storm energy into devastating chain strikes. Exiled from EMBERVEIL for refusing orders, she held the ember throne through three cycles of dark silence and stepped aside the moment its true sovereign returned.' },
  { id:'hero_002', name:'Ash Renn',       frame:'BLAZEGUARD',     faction:'EMBERVEIL', rank:'A',         element:'Fire',      effect:'INCINERATE',      class:'Attacker', cardId:'EMB-02-ASH',      hp:4200, atk:520, def:220, crit:460, about:'Elite vanguard of EMBERVEIL. Ash\'s sword is perpetually wreathed in solar flames capable of melting through any barrier. Born in the volcanic highlands, she fights without hesitation.' },
  { id:'hero_003', name:'Nova Blaine',    frame:'FROSTMEND',      faction:'GLACIARA',  rank:'S',         element:'Ice',       effect:'GLACIATION',      class:'Mage',     cardId:'GLA-01-NOVA',     hp:3000, atk:640, def:155, crit:580, about:'Supreme ice mage of GLACIARA. Nova channels glacial frost into devastating arcane constructs — her crystalline spell-towers and blizzard barriers are considered masterpieces of the frozen battlefield.' },
  { id:'hero_004', name:'Lyra Frost',     frame:'BLOOMWEAVE',     faction:'VERDANIA',  rank:'A',         element:'Nature',    effect:'BLOOM',           class:'Mage',     cardId:'VRD-01-LYRA',     hp:2900, atk:580, def:160, crit:540, about:'Nature mage of VERDANIA. Lyra commands living flora with arcane precision, weaving vines and blossoms into devastating spell constructs that overwhelm enemies with uncontrolled growth.' },
  { id:'hero_005', name:'Guren Tide',     frame:'ROOTGUARD',      faction:'VERDANIA',  rank:'B',         element:'Wind',      effect:'ENTANGLEMENT',    class:'Defender', cardId:'VRD-02-GUREN',    hp:6000, atk:340, def:470, crit:260, about:'Guardian of the VERDANIA woodlands. Guren\'s body is hardened by years of forest training, allowing her to withstand tremendous punishment while ensnaring enemies with enchanted roots.' },
  { id:'hero_006', name:'Sol Frost',      frame:'SOLARBOW',       faction:'SUNSPIRE',  rank:'B',         element:'Holy',      effect:'BLESSING',        class:'Support',  cardId:'SUN-01-SOL',      hp:3700, atk:400, def:230, crit:370, about:'A sacred herald of SUNSPIRE who fires blessed light arrows that both weaken foes and restore allies. His aim is guided by solar energy — once released, his arrows never miss.' },
  { id:'hero_007', name:'Zane Ember',     frame:'FLAMEBLADE',     faction:'EMBERVEIL', rank:'A',         element:'Fire',      effect:'INCINERATE',      class:'Attacker', cardId:'EMB-03-ZANE',     hp:4400, atk:490, def:260, crit:420, about:'Champion of EMBERVEIL\'s warrior order. Zane\'s blade is perpetually wreathed in volcanic flame, cutting through armor as if it were paper. He hunts the corruption spreading from beyond the veil.' },
  { id:'hero_008', name:'Mira Dawn',      frame:'VOIDPHANTOM',    faction:'VOIDMARK',  rank:'S',         element:'Void',      effect:'CORRUPTION',      class:'Attacker', cardId:'VMK-01-MIRA',     hp:3300, atk:610, def:180, crit:590, about:'Shadow phantom of VOIDMARK. Mira strikes before enemies can perceive her presence, vanishing into void space between hits. Her every movement tears small rifts in reality itself.' },
  { id:'hero_009', name:'Kane Light',     frame:'IRONSPIRE',      faction:'SUNSPIRE',  rank:'B',         element:'Holy',      effect:'BLESSING',        class:'Defender', cardId:'SUN-02-KANE',     hp:8000, atk:380, def:620, crit:220, about:'Iron bulwark of SUNSPIRE. Kane\'s sacred armor has never been breached in over 300 battles. He stands between his allies and annihilation without flinching.' },
  { id:'hero_010', name:'Tara Wind',      frame:'EMBERDANCER',    faction:'EMBERVEIL', rank:'A',         element:'Fire',      effect:'FLAMEDANCE',      class:'Support',  cardId:'EMB-04-TARA',     hp:3300, atk:320, def:260, crit:340, about:'EMBERVEIL\'s fire-dancing sentinel. Tara amplifies her allies with volcanic energy while her movements flow like living flame — impossible to track and lethal to approach.' },
  { id:'hero_011', name:'Vera Grove',     frame:'FROSTVEIL',      faction:'GLACIARA',  rank:'A',         element:'Ice',       effect:'PERMAFROST',      class:'Defender', cardId:'GLA-02-VERA',     hp:7000, atk:310, def:570, crit:170, about:'Ancient guardian of GLACIARA\'s frozen tundra. Vera\'s body has been tempered by centuries of blizzards, making her near-indestructible and capable of regenerating rapidly in freezing conditions.' },
  { id:'hero_012', name:'Aura Bloom',     frame:'SOLARMAGE',      faction:'SUNSPIRE',  rank:'S', sovereign:true, element:'Holy', effect:'RADIANCE', class:'Mage',     cardId:'SUN-03-AURA',     hp:3400, atk:760, def:175, crit:700, about:'The Radiant Sovereign of SUNSPIRE — chosen not by bloodline or election but by the light itself during the Ceremony of Ascension. Her brilliance on the battlefield is not considered divine. It is.' },
  { id:'hero_013', name:'Omen Null',      frame:'VOIDOMEN',       faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'VOID_OMEN',       class:'Mage',     cardId:'VMK-03-OMEN',     hp:3000, atk:580, def:155, crit:540, about:'A void scholar who has spent decades studying entities older than recorded history. She perceives abyss energy as constant, layered information. She left VOIDMARK\'s inner court when she realized the court feared what she knew.' },
  { id:'hero_014', name:'Shade Vex',      frame:'DARKSTEP',       faction:'VOIDMARK',  rank:'B',         element:'Void',      effect:'SHADOW',          class:'Attacker', cardId:'VMK-02-SHADE',    hp:3200, atk:500, def:175, crit:490, about:'Assassin of the VOIDMARK faction. Shade strikes from angles that don\'t exist in normal space. Her targets are erased before they can register the attack.' },
  { id:'hero_015', name:'Vex Hollow',     frame:'FROSTWALL',      faction:'GLACIARA',  rank:'B',         element:'Ice',       effect:'CHILL',           class:'Defender', cardId:'GLA-03-VEX',      hp:6600, atk:380, def:530, crit:220, about:'A warrior tempered by GLACIARA\'s most brutal winters. Vex feels no cold and channels frozen energy through her body, converting incoming force into devastating ice-charged counterstrikes.' },
  { id:'hero_016', name:'Brant Forge',    frame:'EMBERWALL',      faction:'EMBERVEIL', rank:'C',         element:'Fire',      effect:'HEATSHIELD',      class:'Defender', cardId:'EMB-05-BRANT',    hp:7200, atk:350, def:580, crit:200, about:'A battle-hardened shield-bearer of EMBERVEIL who uses his body as a living wall, absorbing volcanic strikes and redirecting raw heat into explosive counterattacks.' },
  { id:'hero_017', name:'Colt Vane',      frame:'SNOWMENDER',     faction:'GLACIARA',  rank:'C',         element:'Ice',       effect:'FROSTMEND',       class:'Support',  cardId:'GLA-04-COLT',     hp:4100, atk:280, def:310, crit:220, about:'A field medic of GLACIARA who channels glacial energy to seal wounds and freeze bleeding in real time. He has never lost a patient on the battlefield.' },
  { id:'hero_018', name:'Lyse Dawn',      frame:'SOLARFANG',      faction:'SUNSPIRE',  rank:'A',         element:'Holy',      effect:'SMITE',           class:'Attacker', cardId:'SUN-04-LYSE',     hp:3500, atk:530, def:200, crit:480, about:'A divine huntress of SUNSPIRE who pursues corrupted entities with holy blades charged by direct sunlight. Lyse strikes with blinding speed and vanishes before her targets can register the attack.' },
  { id:'hero_019', name:'Bryn Thorn',     frame:'THORNBLADE',     faction:'VERDANIA',  rank:'C',         element:'Nature',    effect:'TOXIN',           class:'Attacker', cardId:'VRD-04-BRYN',     hp:3800, atk:470, def:190, crit:420, about:'A scrappy brawler from VERDANIA\'s outer villages who forged his fighting style from the wild itself. His strikes carry venomous thorn energy that lingers long after the blow lands.' },
  { id:'hero_020', name:'Kael Rift',      frame:'VOIDWEAVER',     faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'NULLIFY',         class:'Mage',     cardId:'VMK-03-KAEL',     hp:3100, atk:600, def:165, crit:555, about:'A void scholar of VOIDMARK who studies and weaponises dimensional tears. Kael folds space around enemies, trapping them in pocket dimensions where his spells arrive from every angle.' },
  { id:'hero_021', name:'Nyx Flame',      frame:'ASHCALLER',      faction:'EMBERVEIL', rank:'B',         element:'Fire',      effect:'SCORCH',          class:'Mage',     cardId:'EMB-06-NYX',      hp:2900, atk:555, def:155, crit:510, about:'A volatile mage of EMBERVEIL who weaponises wildfire in its purest form. Nyx refuses to contain her power — she simply feeds it. Enemies who survive her opening blast rarely last.' },
  { id:'hero_022', name:'Rook Cinder',    frame:'IRONVEIL',       faction:'EMBERVEIL', rank:'A',         element:'Fire',      effect:'FLAMEGUARD',      class:'Defender', cardId:'EMB-07-ROOK',     hp:6800, atk:370, def:560, crit:210, about:'Steel-willed guardian of EMBERVEIL\'s inner fortress. Rook\'s armour was forged in active volcanic vents and redirects incoming damage as superheated steam.' },
  { id:'hero_023', name:'Vel Spark',      frame:'SPARKWEAVE',     faction:'EMBERVEIL', rank:'C',         element:'Lightning', effect:'VOLTMEND',        class:'Support',  cardId:'EMB-08-VEL',      hp:3600, atk:290, def:230, crit:240, about:'A chaotic young field operative of EMBERVEIL who channels electrical surges to disrupt enemies and jolt fallen allies back into action. Her unpredictable energy is difficult to anticipate.' },
  { id:'hero_024', name:'Dusk Vale',      frame:'GLACIALBLADE',   faction:'GLACIARA',  rank:'S',         element:'Ice',       effect:'SHATTER',         class:'Attacker', cardId:'GLA-05-DUSK',     hp:3400, atk:620, def:200, crit:570, about:'The lone wolf hunter of GLACIARA — an anomaly among the faction\'s warrior elite. Dusk moves through frozen terrain like a living shadow, shattering targets with strikes that exploit brittleness.' },
  { id:'hero_025', name:'Sable Hail',     frame:'WINTERMAGE',     faction:'GLACIARA',  rank:'A',         element:'Ice',       effect:'BLIZZARD',        class:'Mage',     cardId:'GLA-06-SABLE',    hp:2950, atk:595, def:160, crit:545, about:'A storm-class mage of GLACIARA who conjures blizzards on command. Sable prefers overwhelming area coverage over precision: if enough ice falls, nothing survives.' },
  { id:'hero_026', name:'Roan Tusk',      frame:'FROSTBARK',      faction:'GLACIARA',  rank:'B',         element:'Ice',       effect:'ICEWALL',         class:'Defender', cardId:'GLA-07-ROAN',     hp:6900, atk:345, def:550, crit:195, about:'A colossus of GLACIARA who has spent decades hardening his body against arctic extremes. Roan\'s skin crystallises under sustained cold, forming natural ice-plate armour that grows denser with every hit.' },
  { id:'hero_027', name:'Cyren Halo',     frame:'PRISMWEAVE',     faction:'SUNSPIRE',  rank:'A',         element:'Holy',      effect:'ILLUMINATE',      class:'Mage',     cardId:'SUN-05-CYREN',    hp:3050, atk:610, def:160, crit:560, about:'A prism mage of SUNSPIRE who treats combat as a geometry problem. Cyren refracts raw sunlight into precision arcane beams — find the correct angle and a single ray can pass through an entire formation.' },
  { id:'hero_028', name:'Wren Gild',      frame:'HOLYMEND',       faction:'SUNSPIRE',  rank:'B',         element:'Holy',      effect:'SANCTIFY',        class:'Support',  cardId:'SUN-06-WREN',     hp:4000, atk:260, def:290, crit:210, about:'A gentle but unyielding cleric of SUNSPIRE who channels divine light into restorative energy. Wren believes no wound is beyond healing and will exhaust herself before allowing an ally to fall.' },
  { id:'hero_029', name:'Cade Blaze',     frame:'SOLARSTRIKE',    faction:'SUNSPIRE',  rank:'C',         element:'Holy',      effect:'SMITE',           class:'Attacker', cardId:'SUN-07-CADE',     hp:3600, atk:450, def:195, crit:390, about:'A young zealot of SUNSPIRE still proving herself on the battlefield. Cade\'s technique is raw and forward, compensating for inexperience with relentless aggression and unshakeable conviction.' },
  { id:'hero_030', name:'Iris Vale',      frame:'VERDANTFANG',    faction:'VERDANIA',  rank:'S', sovereign:true, element:'Nature', effect:'THORNSTRIKE', class:'Attacker', cardId:'VRD-05-IRIS',     hp:4000, atk:780, def:225, crit:720, about:'The Thornborn Queen of VERDANIA — crowned by the jungle itself during the Night of Blossoming. Iris feels every wound dealt to her forest as if carved into her own skin. On the battlefield she does not hunt her targets. She becomes the terrain they are standing on.' },
  { id:'hero_031', name:'Sage Burl',      frame:'BLOOMKEEP',      faction:'VERDANIA',  rank:'B',         element:'Nature',    effect:'REJUVENATE',      class:'Support',  cardId:'VRD-06-SAGE',     hp:4200, atk:270, def:300, crit:220, about:'A wandering herbalist of VERDANIA carrying centuries of forest medicine. Sage can accelerate a fighter\'s natural healing to impossible rates, closing critical wounds mid-combat.' },
  { id:'hero_032', name:'Rae Vine',       frame:'VERDANSHIELD',   faction:'VERDANIA',  rank:'A',         element:'Nature',    effect:'BARKSKIN',        class:'Defender', cardId:'VRD-07-RAE',      hp:6500, atk:330, def:545, crit:180, about:'A sentinel of VERDANIA who has merged her body with living bark and vine. Rae\'s skin is reinforced by constantly regenerating plant-matter — the longer a fight lasts, the harder she becomes to damage.' },
  { id:'hero_033', name:'Nyx Vael',       frame:'ABYSSALTHRONE',  faction:'VOIDMARK',  rank:'S', sovereign:true, element:'Void', effect:'ABYSS', class:'Defender', cardId:'VMK-04-NYX', hp:9500, atk:500, def:800, crit:300, about:'The unopposed sovereign of VOIDMARK — a void-forged empress whose body has merged with the abyss itself and been reborn stronger. Three challenger factions dissolved attempting to dethrone her. Their names are no longer spoken in VOIDMARK, which here is a fate more feared than death.' },
  { id:'hero_034', name:'Nera Null',      frame:'SOULBIND',       faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'LIFEDRAIN',       class:'Support',  cardId:'VMK-05-NERA',     hp:3800, atk:350, def:250, crit:300, about:'A void medium of VOIDMARK who siphons life force from the battlefield and redistributes it among her allies. Nera walks the thin line between healing and corruption — her methods work.' },
  { id:'hero_036', name:'Vesper Hex',     frame:'SPIRITWEAVE',    faction:'VOIDMARK',  rank:'S',         element:'Void',      effect:'VOID_CURSE',      class:'Mage',     cardId:'VMK-07-VESPER',   hp:3400, atk:640, def:200, crit:580, about:'A supreme void mage of VOIDMARK whose consciousness partially inhabits the space between dimensions. Vesper doesn\'t merely cast spells — she rewrites the rules of engagement at will.' },
  { id:'hero_035', name:'Flux Rend',      frame:'DARKBLADE',      faction:'VOIDMARK',  rank:'B',         element:'Void',      effect:'PHANTOMSTRIKE',   class:'Attacker', cardId:'VMK-06-FLUX',     hp:3500, atk:510, def:180, crit:470, about:'A reckless void-brawler who has partially phased herself into the void to strike from inside the space between moments. Flux hits targets from angles that do not exist.' },
  { id:'hero_037', name:'Aeloria',        frame:'FROZENTHRONE',   faction:'GLACIARA',  rank:'S', sovereign:true, element:'Ice', effect:'SOVEREIGNTY', class:'Mage',     cardId:'GLA-08-AELORIA',  hp:3500, atk:780, def:185, crit:710, about:'The original sovereign who built GLACIARA from nothing and sacrificed her throne to seal an elder darkness. Crystallized into legend for centuries, she has awakened to find pretenders sitting her seat. Her power simply makes every other ice mage feel like they are standing in snow while she commands the glacier.' },
  { id:'hero_038', name:'Veyra Null',     frame:'VOIDWEAVE',      faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'VOID_PULSE',      class:'Mage',     cardId:'VMK-08-VEYRA',    hp:3100, atk:560, def:185, crit:510, about:'A former scholar of forbidden void texts who crossed the line between knowledge and corruption. Veyra no longer reads the void — she channels it directly through her nervous system.' },
  { id:'hero_039', name:'Caelum Vane',    frame:'DAWNGUARD',      faction:'SUNSPIRE',  rank:'A',         element:'Holy',      effect:'DIVINE_SHIELD',   class:'Defender', cardId:'SUN-08-CAELUM',   hp:6800, atk:350, def:580, crit:220, about:'A veteran paladin of SUNSPIRE who has survived more campaigns than any other active knight on the line. His sacred shield has absorbed blows that would have ended entire battles.' },
  { id:'hero_041', name:'Ravenna Blaze',  frame:'EMBRATHRONE',    faction:'EMBERVEIL', rank:'S', sovereign:true, element:'Fire', effect:'SOVEREIGN_FLAME', class:'Mage',   cardId:'EMB-09-RAVENNA',  hp:4200, atk:820, def:235, crit:750, about:'The original sovereign of EMBERVEIL — swallowed by a dimensional rift three cycles of the volcanic moon ago while sealing a catastrophic breach. She has returned carrying fire from the other side of dimensions, fire that burns even those immune to ordinary flame.' },
  { id:'hero_040', name:'Sora Rime',      frame:'FROSTDANCER',    faction:'GLACIARA',  rank:'A',         element:'Ice',       effect:'SHATTER',         class:'Attacker', cardId:'GLA-09-SORA',     hp:3300, atk:540, def:195, crit:490, about:'A blade-dancer of GLACIARA who incorporates ice formation into her fighting style mid-combat. Sora conjures frost platforms and ice constructs as she moves, using the environment she creates against her opponents in the same unbroken fluid motion.' },
  { id:'hero_042', name:'Crysta Venn',    frame:'FROSTPULSE',     faction:'GLACIARA',  rank:'A',         element:'Ice',       effect:'CHILL',           class:'Mage',     cardId:'GLA-10-CRYSTA',   hp:3100, atk:520, def:188, crit:472, about:'A crystallomancer from GLACIARA\'s deep research halls who treats combat like a theorem — isolate the variable, reduce it to zero. Her precision is unnerving, her frost constructs are flawless.' },
  { id:'hero_043', name:'Kitsuri',        frame:'FOXFLAME',       faction:'EMBERVEIL', rank:'S',         element:'Fire',      effect:'BURN',            class:'Attacker', cardId:'EMB-10-KITSURI',  hp:4100, atk:730, def:248, crit:665, about:'A nine-tailed kitsune swordswoman from EMBERVEIL\'s volcanic highlands who inherited her fox spirit bloodline\'s fire through every one of her tails. When her ninth tail ignites, the battle is already over.' },
  { id:'hero_044', name:'Fennara Gale',   frame:'WINDSPRITE',     faction:'VERDANIA',  rank:'A',         element:'Wind',      effect:'SHATTER',         class:'Mage',     cardId:'VRD-08-FENN',     hp:3000, atk:535, def:182, crit:485, about:'A fox-spirit mage from VERDANIA\'s windswept canopy who draws power from the boundary between forest gale and root-bound earth. Her spells cross wind and nature with a fluidity that feels less like power and more like the forest changing its mind at speed.' },
  { id:'hero_045', name:'Umbra Shade',    frame:'DARKWEAVE',      faction:'VOIDMARK',  rank:'B',         element:'Void',      effect:'VOID_CURSE',      class:'Mage',     cardId:'VMK-09-UMBRA',    hp:3200, atk:500, def:172, crit:455, about:'A void-dark dual-channeler of VOIDMARK who weaponizes the tension between dark energy and void space. Umbra operates in the frequency where they cancel each other out — the most destructive thing in either spectrum.' },
  { id:'hero_046', name:'Kaiden Rhayne',  frame:'VOIDCANNON',     faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'SHADOW',          class:'Attacker', cardId:'VMK-10-KAIDEN',   hp:4400, atk:498, def:258, crit:445, about:'Commander of VOIDMARK\'s void-elite rapid response force. His void-enhanced firearms don\'t fire conventional rounds; they fire collapsed dimensional points that arrive before they are shot.' },
  { id:'hero_047', name:'Morvan Hex',     frame:'ABYSSSCRIBE',    faction:'VOIDMARK',  rank:'A',         element:'Void',      effect:'LIFEDRAIN',       class:'Mage',     cardId:'VMK-11-MORVAN',   hp:3300, atk:545, def:185, crit:495, about:'A dark arts scholar of VOIDMARK who decided that understanding darkness was insufficient — immersion was required. He still writes detailed academic papers on every spell he casts. After the battle.' },
  { id:'hero_048', name:'Aeron Sunblade', frame:'DAWNBLADE',      faction:'SUNSPIRE',  rank:'A',         element:'Holy',      effect:'SMITE',           class:'Attacker', cardId:'SUN-09-AERON',    hp:4100, atk:508, def:238, crit:462, about:'A dual-blade paladin of SUNSPIRE who rejected the shield-and-hammer tradition to develop a faster, more aggressive interpretation of holy combat. His superior officers initially objected. They stopped after the third campaign.' },
  { id:'hero_049', name:'Lyra Flame',     frame:'HOLYFLAME',      faction:'SUNSPIRE',  rank:'B',         element:'Holy',      effect:'BLESSING',        class:'Support',  cardId:'SUN-10-LYRA',     hp:3500, atk:345, def:242, crit:292, about:'One of three Flame sisters. Born beside Nyx Flame of EMBERVEIL and Terra Flame of VERDANIA, and uniquely blessed with holy light where her sisters carry fire and earth. The light pulled in a direction she could not ignore.' },
  { id:'hero_050', name:'Terra Flame',    frame:'EARTHFLAME',     faction:'VERDANIA',  rank:'B',         element:'Nature',    effect:'TOXIN',           class:'Mage',     cardId:'VRD-09-TERRA',    hp:3700, atk:435, def:218, crit:388, about:'One of three Flame sisters. She watched one sister burn everything she touches and another illuminate it, and chose instead to grow things. She is gentle in three languages and devastating in all of them.' },
  { id:'hero_051', name:'Mira Vael',      frame:'VOIDCOUNSEL',    faction:'VOIDMARK',  rank:'S',         element:'Void',      effect:'VOID_CURSE',      class:'Mage',     cardId:'VMK-12-MIRA',     hp:3400, atk:640, def:202, crit:580, about:'VOIDMARK\'s sovereign Nyx Vael keeps no inner council — except one. Mira Vael is not royal by blood, not a general; she is simply the one person in VOIDMARK whose counsel Nyx listens to without exception. No one knows what was said between them the day that arrangement began.' },
  { id:'hero_052', name:'Lumara Sol',     frame:'SOLARWEAVE',     faction:'SUNSPIRE',  rank:'B',         element:'Holy',      effect:'BLESSING',        class:'Mage',     cardId:'SUN-11-LUMARA',   hp:3250, atk:480, def:185, crit:432, about:'A solar-channeling mage of SUNSPIRE who built her entire magical vocabulary out of concentrated sunlight before she learned a single offensive spell. She is considerably more effective at reducing things to ash than her academic background suggests.' },
  { id:'hero_053', name:'Avara Plume',    frame:'PLUMEWARDEN',    faction:'VERDANIA',  rank:'A',         element:'Nature',    effect:'THORNSTRIKE',     class:'Mage',     cardId:'VRD-10-AVARA',    hp:3200, atk:542, def:188, crit:492, about:'A nature mage of VERDANIA who arrived at her magical specialty by accident — she was trying to communicate with a wounded crow and ended up channeling the entire forest\'s awareness through the bird\'s dying perception.' },
];

// ─── Sovereign heroes (one per faction) ──────────────────────────────────────
export const SOVEREIGN_HEROES = HEROES.filter(h => h.sovereign);

// ─── Helper functions ─────────────────────────────────────────────────────────
export const getHeroById        = (id)      => HEROES.find(h => h.id === id);
export const getHeroesByFaction = (faction) => HEROES.filter(h => h.faction === faction);
export const getHeroesByRank    = (rank)    => HEROES.filter(h => h.rank === rank);

// ─── Enemy bosses (one per chapter) ──────────────────────────────────────────
export const BOSSES = [
  { chapter:1,  name:'Lysha the Glacial Empress',  title:'SHATTERED VEIL',      faction:'GLACIARA', image:'/assets/enemy/boss_001.webp', desc:'An ancient ice empress who shattered reality itself to rule the frozen domains. Commands absolute zero temperatures that stop even divine energy in its tracks.' },
  { chapter:2,  name:'Pyrevex the Ashen Drake',    title:'ASHEN INFERNO',       faction:'EMBERVEIL', image:'/assets/enemy/boss_002.webp', desc:'A volcanic dragon-beast born from the heart of erupting mountains. Its breath does not merely burn — it consumes matter on a dimensional level.' },
  { chapter:3,  name:'Aurariel the Light Maiden',  title:'DAWN OF RADIANCE',    faction:'SUNSPIRE',  image:'/assets/enemy/boss_003.webp', desc:'A fallen celestial guardian corrupted by forbidden holy rituals. She wields radiant light as a weapon of annihilation rather than salvation.' },
  { chapter:4,  name:'Thornqueen Sylva',           title:'THORNWALL',           faction:'VERDANIA',  image:'/assets/enemy/boss_004.webp', desc:'The ancient sovereign of the primordial forest, driven mad by corruption. Sylva commands living thorn walls that close around enemies like a fist.' },
  { chapter:5,  name:'Verdara the Bloom Devourer', title:'VERDANT RUIN',        faction:'VERDANIA',  image:'/assets/enemy/boss_005.webp', desc:'A twisted nature spirit consuming all life to fuel its endless hunger. The forest it passes through is never seen again.' },
  { chapter:6,  name:'Shade Queen Morveth',        title:'SHADOWBLOOM',         faction:'VOIDMARK',  image:'/assets/enemy/boss_006.webp', desc:'A dark ruler who has merged her consciousness with the shadow bloom, a parasitic void entity that feeds on natural energy.' },
  { chapter:7,  name:'The Abyssal Gate Keeper',   title:'ABYSSAL GATE',        faction:'VOIDMARK',  image:'/assets/enemy/boss_007.webp', desc:'An entity that is neither alive nor dead — the consciousness of the dimensional gate itself, manifested as an entity of pure void will.' },
  { chapter:8,  name:'Eclipsis the Dark Sun',      title:'ECLIPSE RISING',      faction:'VOIDMARK',  image:'/assets/enemy/boss_008.webp', desc:'A catastrophic fusion of holy light and void darkness. Eclipsis exists in the precise moment of an eclipse, and strikes with both energies simultaneously.' },
  { chapter:9,  name:'The Celestial Fracture',     title:'CELESTIAL FRACTURE',  faction:'SUNSPIRE',  image:'/assets/enemy/boss_009.webp', desc:'A fracture in the heavens given form — an entity of pure celestial energy gone critical, shattering the fabric of sky and void alike.' },
  { chapter:10, name:'Vex the Void Queen',         title:"VOID QUEEN'S REIGN",  faction:'VOIDMARK',  image:'/assets/enemy/boss_010.webp', desc:'A self-proclaimed queen of the deepest void, commanding armies of dimensional aberrations. Her throne is a collapsed star in the space between worlds.' },
  { chapter:11, name:'The Titan Awakened',         title:"TITAN'S MARCH",       faction:'EMBERVEIL', image:'/assets/enemy/boss_011.webp', desc:'A primordial titan of volcanic rock and magma who slept for ten thousand years. Its awakening causes earthquakes across three factions simultaneously.' },
  { chapter:12, name:'Chronovex the Time Eater',   title:"TIME'S END",          faction:'VOIDMARK',  image:'/assets/enemy/boss_012.webp', desc:'An entity that consumes temporal energy — it ages enemies by centuries in seconds and reverses its own damage by rewinding its personal timeline.' },
  { chapter:13, name:'Blizzara the Eternal Winter', title:'ETERNAL WINTER',     faction:'GLACIARA',  image:'/assets/enemy/boss_013.webp', desc:'A catastrophic winter entity that threatens to freeze all five factions under an eternal glacier. Even GLACIARA sovereigns fear what it represents.' },
  { chapter:14, name:'The Crimson Emperor',        title:'CRIMSON EMPIRE',      faction:'EMBERVEIL', image:'/assets/enemy/boss_014.webp', desc:'A fallen sovereign of EMBERVEIL who rejected the dimensional fire and sought to conquer all factions under a blood-red banner of raw domination.' },
  { chapter:15, name:'The World Eater',            title:"WORLD'S LAST HOUR",   faction:'VOIDMARK',  image:'/assets/enemy/boss_015.webp', desc:'An entity from outside the known dimensions whose only purpose is consumption. Every hero, every faction, every living thing in the realm stands against it.' },
];

// ─── Story chapters ────────────────────────────────────────────────────────────
export const CHAPTERS = [
  { id:1,  title:'Shattered Veil',      theme:'Ice',        color:'#00B4D8', desc:'The dimensional veil between worlds shatters in GLACIARA territory. An ancient empress emerges from the frozen rift, and the realm faces its first true crisis in a generation.' },
  { id:2,  title:'Ashen Inferno',       theme:'Fire',       color:'#FF4500', desc:'Volcanic catastrophe tears through EMBERVEIL\'s highlands as a dimensional drake awakens. Ash and ruin spread across the faction\'s territory.' },
  { id:3,  title:'Dawn of Radiance',    theme:'Holy',       color:'#D4A017', desc:'A corrupted celestial guardian descends on SUNSPIRE, twisting the light itself into a weapon. The holy order fights to reclaim its sacred territory from divine darkness.' },
  { id:4,  title:'Thornwall',           theme:'Nature',     color:'#2ECC71', desc:'An ancient thorn queen seals VERDANIA\'s forest behind impenetrable walls of living thorn. Heroes fight through layer after layer of hostile terrain to reach the source.' },
  { id:5,  title:'Verdant Ruin',        theme:'Nature',     color:'#27AE60', desc:'A bloom devourer consumes VERDANIA\'s life energy, leaving devastation in its wake. The forest that survived millennia faces extinction in days.' },
  { id:6,  title:'Shadowbloom',         theme:'Dark',       color:'#9B59B6', desc:'A dark queen merges with a parasitic void bloom, corrupting VOIDMARK\'s border territories. Shadow and unnatural growth consume everything it touches.' },
  { id:7,  title:'Abyssal Gate',        theme:'Void',       color:'#6C3483', desc:'The dimensional gate between worlds activates involuntarily, threatening to collapse the boundary between the realm and the void. A gate keeper entity manifests.' },
  { id:8,  title:'Eclipse Rising',      theme:'Void/Holy',  color:'#8E44AD', desc:'A fusion of holy light and void darkness manifests during a catastrophic eclipse. Both SUNSPIRE and VOIDMARK factions mobilize as reality itself becomes unstable.' },
  { id:9,  title:'Celestial Fracture',  theme:'Holy',       color:'#F39C12', desc:'A fracture in the heavens widens beyond any hero\'s ability to contain it individually. The sky cracks and entities pour through the breach.' },
  { id:10, title:"Void Queen's Reign",  theme:'Void',       color:'#7D3C98', desc:'A self-proclaimed void queen establishes dominion over dimensional space itself. Her armies of aberrations begin systematic incursions into every faction simultaneously.' },
  { id:11, title:"Titan's March",       theme:'Fire/Earth', color:'#E74C3C', desc:'A primordial titan of volcanic rock awakens from ten millennia of slumber. Its march triggers geological collapse across three faction territories.' },
  { id:12, title:"Time's End",          theme:'Void',       color:'#5D6D7E', desc:'The Chronovex entity threatens to consume the realm\'s temporal energy, aging everything it touches by centuries. Heroes must fight outside the normal flow of time.' },
  { id:13, title:'Eternal Winter',      theme:'Ice',        color:'#85C1E9', desc:'A catastrophic winter entity builds toward an eternal freeze that would end life in all five factions. Even GLACIARA\'s sovereign cannot contain it alone.' },
  { id:14, title:'Crimson Empire',      theme:'Fire',       color:'#C0392B', desc:'A fallen EMBERVEIL sovereign returns to claim all five factions under a blood empire. Former allies become enemies as the crimson tide advances.' },
  { id:15, title:"World's Last Hour",   theme:'All',        color:'#2C3E50', desc:'The World Eater arrives. Every hero, every faction, every living thing in the realm stands against a single entity whose only purpose is the end of all things.' },
];
